version: '3.5'

services:
  website:
    container_name: eos-website-dev
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../../:/var/www/eos-website
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - "8000:80"
