version: '3.5'

services:
  database:
    container_name: eos-db-dev
    image: 'mariadb:latest'
    volumes:
      - ../../database/sql_scripts/eos_website.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - ../../.env
    ports:
      - '3306:3306'
    networks:
      eos_net:


  website:
    container_name: eos-website-dev
    depends_on:
      - database
    env_file:
      - ../../.env
    environment: 
      WAIT_HOSTS: database:3306
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    volumes:
      - ../../media:/var/www/eos-website/media
    ports:
      - "8000:80"
    networks:
      eos_net:

  pma:
    container_name: eos-pma-dev
    image: 'phpmyadmin/phpmyadmin:latest'
    env_file:
      - ../../.env
    ports:
      - '8001:80'
    networks:
      eos_net:

networks:
  eos_net: