version: '3.5'

services:

  database:
    container_name: eos-db-prod
    image: 'mariadb:latest'
    volumes:
      - '../../database/data:/var/lib/mysql'
    env_file:
      - ../../.env
    ports:
      - '3306:3306'
    networks:
      eos_net:

  website:
    depends_on:
      - database
    container_name: eos-website-prod
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    volumes:
      - static_volume:/var/www/eos-website/static
    env_file:
      - ../../.env
    command: bash -c "python manage.py migrate --noinput && python manage.py collectstatic -c --noinput && python manage.py compress --force && gunicorn -c config/gunicorn/gunicorn.production.conf --env DJANGO_SETTINGS_MODULE=eos_website.settings.production --bind 0.0.0.0:8000 eos_website.wsgi"
    expose:
      - 8000
    networks:
      eos_net:

  nginx:
    container_name: nginx-eos-website
    depends_on:
      - website
    build:
      context: ../../
      dockerfile: docker/production/nginx.Dockerfile
    volumes:
      - static_volume:/var/www/eos-website/static
    ports:
    - "8000:80"
    networks:
      eos_net:
  pma:
    container_name: eos-pma-prod
    image: 'phpmyadmin/phpmyadmin:latest'
    env_file:
      - ../../.env
    ports:
      - '8001:80'
    networks:
      eos_net:

networks:
  eos_net:

volumes:
  static_volume:
