version: '3.5'

services:
  database:
    container_name: eos-db-prod
    image: 'mariadb:latest'
    restart: unless-stopped
    volumes:
      - ../../database/sql_scripts/eos_website.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file:
      - ../../.env
    expose:
      - 3306
    networks:
      eos_net:

  website:
    depends_on:
      - database
    container_name: eos-website-prod
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    volumes:
      - static_volume:/var/www/eos-website/static
      - ../../media:/var/www/eos-website/media
    env_file:
      - ../../.env
    environment: 
      WAIT_HOSTS: database:3306
    expose:
      - 80
    networks:
      eos_net:
  
  nginx:
    container_name: nginx-eos-website
    depends_on:
      - website
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: docker/production/nginx.Dockerfile
    volumes:
      - static_volume:/var/www/eos-website/static
    ports:
      - "80:80"
    networks:
      eos_net:
  pma:
    container_name: eos-pma-prod
    image: 'phpmyadmin/phpmyadmin:latest'
    env_file:
      - ../../.env
    restart: unless-stopped
    expose: 
      - 80
    networks:
      eos_net:

networks:
  eos_net:

volumes:
  static_volume:
